# Generated by Django 4.1.7 on 2023-03-12 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Censor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=200)),
                ("fag", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name_plural": "Censorer",
            },
        ),
        migrations.CreateModel(
            name="Lærer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name_plural": "Lærere",
            },
        ),
        migrations.CreateModel(
            name="Skole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=200)),
                ("adresse", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Skoler",
            },
        ),
        migrations.CreateModel(
            name="Skoleklasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=50)),
                (
                    "lærere",
                    models.ManyToManyField(
                        related_name="klasser", to="censor_app.lærer"
                    ),
                ),
                (
                    "skole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="censor_app.skole",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skoleklasser",
            },
        ),
        migrations.AddField(
            model_name="lærer",
            name="skole",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personale",
                to="censor_app.skole",
            ),
        ),
        migrations.CreateModel(
            name="Eksamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=200)),
                (
                    "dato",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "censor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="censor_app.censor",
                    ),
                ),
                (
                    "lærer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="censor_app.lærer",
                    ),
                ),
                (
                    "skole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eksamener",
                        to="censor_app.skole",
                    ),
                ),
                (
                    "skoleklasse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="censor_app.skoleklasse",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Eksamener",
            },
        ),
        migrations.AddField(
            model_name="censor",
            name="skole",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="censorer",
                to="censor_app.skole",
            ),
        ),
    ]
