# Generated by Django 4.1.7 on 2023-03-11 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Censor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Eksamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=200)),
                (
                    "dato",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "censor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="censor_app.censor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lærer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Skole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=200)),
                ("addresse", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Skoleklasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=50)),
                ("lærere", models.ManyToManyField(blank=True, to="censor_app.lærer")),
                (
                    "skole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="censor_app.skole",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lærer",
            name="skole",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personale",
                to="censor_app.skole",
            ),
        ),
        migrations.CreateModel(
            name="EksamensCensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "censor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_censor",
                        to="censor_app.censor",
                    ),
                ),
                (
                    "eksamen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_eksamen",
                        to="censor_app.eksamen",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eksamen",
            name="lærer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="censor_app.lærer",
            ),
        ),
        migrations.AddField(
            model_name="eksamen",
            name="skoleklasse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="censor_app.skoleklasse"
            ),
        ),
        migrations.AddField(
            model_name="censor",
            name="skole",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="censorer",
                to="censor_app.skole",
            ),
        ),
    ]
