# Generated by Django 4.1.7 on 2023-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("censor_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="censor",
            options={"verbose_name_plural": "Censorer"},
        ),
        migrations.AlterModelOptions(
            name="eksamen",
            options={"verbose_name_plural": "Eksamener"},
        ),
        migrations.AlterModelOptions(
            name="eksamenscensor",
            options={"verbose_name_plural": "Eksamenscensorer"},
        ),
        migrations.AlterModelOptions(
            name="lærer",
            options={"verbose_name_plural": "Lærere"},
        ),
        migrations.AlterModelOptions(
            name="skole",
            options={"verbose_name_plural": "Skoler"},
        ),
        migrations.AlterModelOptions(
            name="skoleklasse",
            options={"verbose_name_plural": "Skoleklasser"},
        ),
        migrations.AlterField(
            model_name="lærer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
