# Generated by Django 4.1.7 on 2023-03-07 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("censor_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personale",
                to="censor_app.school",
            ),
        ),
    ]
