# Generated by Django 4.1.7 on 2023-03-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("censor_app", "0003_censor_fag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EksamensCensor",
        ),
    ]
