# Generated by Django 4.1.7 on 2023-03-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("censor_app", "0004_delete_eksamenscensor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skole",
            old_name="addresse",
            new_name="adresse",
        ),
        migrations.AlterField(
            model_name="skoleklasse",
            name="lærere",
            field=models.ManyToManyField(
                blank=True, related_name="klasser", to="censor_app.lærer"
            ),
        ),
    ]
