# Generated by Django 4.1.7 on 2023-03-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("censor_app", "0005_rename_addresse_skole_adresse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censor",
            name="navn",
            field=models.EmailField(max_length=254),
        ),
    ]
