# Generated by Django 4.1.7 on 2023-03-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("censor_app", "0006_alter_censor_navn"),
    ]

    operations = [
        migrations.AddField(
            model_name="censor",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="censor",
            name="navn",
            field=models.CharField(max_length=200),
        ),
    ]
